
data.json:
	cp ../../projects/fml15/index.html .
	cp ../../projects/fml15/bundle.min.js .
	cp ../../projects/fml15/data.json .
	cp ../../projects/fml15/image.png .
	cp ../../projects/fml15/single.svg .
	cp ../../projects/fml15/custom.css .
