# graphic for Yahoo! Finance

all: graphic

.PHONY: graphic

graphic:
	cp ../fm/26/index.html graphic
	cp ../fm/26/data.json graphic
	cp ../fm/26/styles.css graphic
	cp ../fm/26/bundle.min.js graphic
