
.PHONY: verizon2018

all: verizon2018

verizon2018:
	cp ../../../single/verizon2018/test.html verizon2018/index.html
	cp ../../../single/verizon2018/bundle.min.js verizon2018
	cp ../../../single/verizon2018/bins2018.json verizon2018
	cp ../../../single/verizon2018/verizon.png verizon2018
	cp ../../../single/data/us.json data
