all: tree2

.PHONY: tree1 tree2

tree1:
	cp ../../tree1/index.html tree1
	cp ../../tree1/*.csv tree1
	cp ../../tree1/*.css tree1
	cp ../../tree1/bundle.min.js tree1

tree2:
	cp ../../tree2/index.html tree2
	cp ../../tree2/*.csv tree2
	cp ../../tree2/*.css tree2
	cp ../../tree2/bundle.min.js tree2

