all: 3 4

.PHONY: 3 4

3:
	cp ~/Sites/menet/3/test.html 3/index.html
	cp ~/Sites/menet/3/data.json 3
	cp ~/Sites/menet/3/bundle.min.js 3

4:
	cp ~/Sites/menet/4/test.html 4/index.html
	cp ~/Sites/menet/4/data.json 4
	cp ~/Sites/menet/4/bundle.min.js 4

