copy:
	cp ~/Sites/bootstrap/docs/quakes/index.html .
	cp ~/Sites/bootstrap/docs/quakes/alaska.html .
	cp ~/Sites/bootstrap/docs/quakes/explorer.html .
	cp ~/Sites/bootstrap/docs/quakes/observable.svg .
