
# NOTE...
#
#    Change the link in `index.html` to use the bootstrap CDN:
#
# <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" />
#


all:
	cp ../../bootstrap/homepage/index.html .
	cp ../../bootstrap/homepage/product.css .
	cp ../../bootstrap/homepage/styles.css .
	cp ../../bootstrap/homepage/favicon.png .
	
	cp ../../bootstrap/homepage/graphic/index.html    graphic
	cp ../../bootstrap/homepage/graphic/bundle.min.js graphic
