
all:
	cp ../../bootstrap/homepage/index.html .
	cp ../../bootstrap/homepage/product.css .
	cp ../../bootstrap/homepage/styles.css .
	cp ../../bootstrap/homepage/favicon.png .
	
	cp ../../bootstrap/homepage/graphic/index.html    graphic
	cp ../../bootstrap/homepage/graphic/bundle.min.js graphic
