all: hpsi

.PHONY: hpsi

# Latest from d3-components
hpsi:
#	cp ~/Sites/d3-components/hpsi/index.html        hpsi
#	cp ~/Sites/d3-components/hpsi/bundle.min.js     hpsi
#	cp ~/Sites/d3-components/hpsi/data.json         hpsi
#	cp ~/Sites/d3-components/hpsi/demo.html         hpsi
#	cp ~/Sites/d3-components/hpsi/bootstrap.min.css hpsi

#	cp ~/Sites/d3-components/hpsi-jun/index.html        hpsi-jun
#	cp ~/Sites/d3-components/hpsi-jun/bundle.min.js     hpsi-jun
#	cp ~/Sites/d3-components/hpsi-jun/data.json         hpsi-jun
#	cp ~/Sites/d3-components/hpsi-jun/demo.html         hpsi-jun
#	cp ~/Sites/d3-components/hpsi-jun/bootstrap.min.css hpsi-jun

	cp ~/Sites/d3-components/mlss/index.html        mlss
	cp ~/Sites/d3-components/mlss/bundle.min.js     mlss
	cp ~/Sites/d3-components/mlss/data.tsv          mlss
	cp ~/Sites/d3-components/mlss/demo.html         mlss
	cp ~/Sites/d3-components/mlss/bootstrap.min.css mlss
