all: hpsi

.PHONY: hpsi

# Latest from d3-components
hpsi:
	cp ~/Sites/d3-components/hpsi/index.html        hpsi
	cp ~/Sites/d3-components/hpsi/bundle.min.js     hpsi
	cp ~/Sites/d3-components/hpsi/data.json         hpsi
	cp ~/Sites/d3-components/hpsi/demo.html         hpsi
	cp ~/Sites/d3-components/hpsi/bootstrap.min.css hpsi
