
# -----------------------------------
# data shared by colorado prototypes
# -----------------------------------

all:
	cp -r ../../../../colorado11/tiles .
	cp ../../../../shale3/shalegas.json .
	cp ../../../../colorado2/co.json .
	cp ../../../../colorado6/file.json .
