
# -----------------------------------
# data shared by colorado prototypes
# -----------------------------------

tiles:
	cp -r ../../../../colorado11/tiles .

shale:
	cp ../../../../shale3/shalegas.json .

states:
	cp ../../../../colorado2/co.json .
