all: fm6 fm7

.PHONY: 6 7

fm5:
	cp ../../fm5/index.html .
	cp ../../fm5/*.csv .
	cp ../../fm5/bundle.min.js .

fm6:
	cp ../../fm6/index.html 6
	cp ../../fm6/*.csv 6
	cp ../../fm6/bundle.min.js 6

fm7:
	cp ../../fm7/index.html 7
	cp ../../fm7/*.csv 7
	cp ../../fm7/bundle.min.js 7
