all: hpsi6

.PHONY: fm3 fm5 fm6 fm7 fm8 fm9 fm10 fm11 fm12 fm16 fm27 fms fmr1 map1 map2 hpsi0 components0 gif talk talk2 iframe

iframe:
	cp ~/Sites/gist/e5ab20468d5d1252b5ed0bb69e5a432f/index.html iframe
	cp ~/Sites/gist/e5ab20468d5d1252b5ed0bb69e5a432f/graphic.html iframe
	cp ~/Sites/gist/e5ab20468d5d1252b5ed0bb69e5a432f/d3.min.js iframe

talk:
	cp ~/Sites/fm/talk/index.html talk
	cp ~/Sites/fm/talk/stylesheets/* talk/stylesheets
	cp ~/Sites/fm/talk/images/* talk/images

talk2:
	cp ~/Sites/fm/talk2/index.html     talk2
	cp ~/Sites/fm/talk2/d3.v3.min.js   talk2
	cp ~/Sites/fm/talk2/stack.v1.js    talk2
	cp ~/Sites/fm/talk2/stylesheet.css talk2
	cp ~/Sites/fm/talk2/graphics/0/*   talk2/graphics/0
	cp ~/Sites/fm/talk2/graphics/0a/*  talk2/graphics/0a
	cp ~/Sites/fm/talk2/graphics/1/*   talk2/graphics/1
	cp ~/Sites/fm/talk2/graphics/2/*   talk2/graphics/2
	cp ~/Sites/fm/talk2/graphics/3/*   talk2/graphics/3
	cp ~/Sites/fm/talk2/graphics/4/*   talk2/graphics/4
	cp ~/Sites/fm/talk2/graphics/5/*   talk2/graphics/5
	cp ~/Sites/fm/talk2/graphics/6/*   talk2/graphics/6


students9:
	cp ~/Sites/fm/students/9/bundle.min.js students/9
	cp ~/Sites/fm/students/9/index.html students/9
	cp ~/Sites/fm/students/9/styles.css students/9
	cp ~/Sites/fm/students/9/iframe.html students/9
	cp ~/Sites/fm/students/9/custom.css students/9

students8:
	cp ~/Sites/fm/students/8/graphic.zip students/8

students7:
	cp ~/Sites/fm/students/7/final.gif students/7

students6:
	cp ~/Sites/fm/students/6/iframe.html students/6
	cp ~/Sites/fm/students/6/custom.css students/6
	cp ~/Sites/fm/students/6/index.html students/6
	cp ~/Sites/fm/students/6/styles.css students/6
	cp ~/Sites/fm/students/6/d3.min.js  students/6

students5:
	cp ~/Sites/fm/students/5/iframe.html students/5
	cp ~/Sites/fm/students/5/custom.css students/5
	cp ~/Sites/fm/students/5/index.html students/5
	cp ~/Sites/fm/students/5/styles.css students/5
	cp ~/Sites/fm/students/5/d3.min.js  students/5

students4:
	cp ~/Sites/fm/students/4/iframe.html students/4
	cp ~/Sites/fm/students/4/custom.css students/4
	cp ~/Sites/fm/students/4/index.html students/4
	cp ~/Sites/fm/students/4/styles.css students/4
	cp ~/Sites/fm/students/4/d3.min.js  students/4

students3:
	cp ~/Sites/fm/students/3/index.html students/3
	cp ~/Sites/fm/students/3/styles.css students/3
	cp ~/Sites/fm/students/3/d3.min.js  students/3

students2:
	cp ~/Sites/fm/students/2/index.html students/2
	cp ~/Sites/fm/students/2/styles.css students/2
	cp ~/Sites/fm/students/2/d3.min.js  students/2

students1:
	cp ~/Sites/fm/students/1/index.html students/1
	cp ~/Sites/fm/students/1/styles.css students/1
	cp ~/Sites/fm/students/1/d3.min.js  students/1

twitter18:
	cp ~/Sites/fm/twitter/18/index.html twitter/18
	cp ~/Sites/fm/twitter/18/source.html twitter/18
	cp ~/Sites/fm/twitter/18/styles.css twitter/18
	cp ~/Sites/fm/twitter/18/bundle.min.js twitter/18
	cp ~/Sites/fm/twitter/data/FannieMaeTwitterMentions_Intelligence.csv twitter/data

twitter16:
	cp ~/Sites/fm/twitter/16/index.html twitter/16
	cp ~/Sites/fm/twitter/16/styles.css twitter/16
	cp ~/Sites/fm/twitter/16/bundle.min.js twitter/16
	cp ~/Sites/fm/twitter/16/data.json twitter/16

twitter14:
	cp ~/Sites/fm/twitter/14/index.html twitter/14
	cp ~/Sites/fm/twitter/14/styles.css twitter/14
	cp ~/Sites/fm/twitter/14/bundle.min.js twitter/14
	cp ~/Sites/fm/twitter/14/data.json twitter/14

twitter6:
	cp ~/Sites/fm/twitter/6/index.html twitter/6
	cp ~/Sites/fm/twitter/6/styles.css twitter/6
	cp ~/Sites/fm/twitter/6/bundle.min.js twitter/6

twitter5:
	cp ~/Sites/fm/twitter/5/index.html twitter/5
	cp ~/Sites/fm/twitter/5/styles.css twitter/5
	cp ~/Sites/fm/twitter/5/bundle.min.js twitter/5
	cp ~/Sites/fm/twitter/data/TwitterPerformance_FannieMae_June15May16.csv twitter/data

twitter3:
	cp ~/Sites/fm/twitter/3/index.html twitter/3
	cp ~/Sites/fm/twitter/3/styles.css twitter/3
	cp ~/Sites/fm/twitter/3/bundle.min.js twitter/3
	cp ~/Sites/fm/twitter/data/TwitterPerformance_FannieMae_June15May16.csv twitter/data

hpsi6:
	cp ~/Sites/fm/hpsi/6/index.html    hpsi/6
	cp ~/Sites/fm/hpsi/6/styles.css    hpsi/6
	cp ~/Sites/fm/hpsi/6/bundle.min.js hpsi/6
	cp ~/Sites/fm/hpsi/6/data.csv      hpsi/6

hpsi5:
	cp ~/Sites/fm/hpsi/5/index.html    hpsi/5
	cp ~/Sites/fm/hpsi/5/styles.css    hpsi/5
	cp ~/Sites/fm/hpsi/5/bundle.min.js hpsi/5
	cp ~/Sites/fm/hpsi/5/data.csv      hpsi/5

hpsi4:
	cp ~/Sites/fm/hpsi/4/index.html hpsi/4
	cp ~/Sites/fm/hpsi/4/styles.css hpsi/4
	cp ~/Sites/fm/hpsi/4/bundle.min.js hpsi/4
	cp ~/Sites/fm/hpsi/data/data.csv hpsi/data

components0:
	cp ~/Sites/fm/hpsi/1/index.html components0
	cp ~/Sites/fm/hpsi/1/styles.css components0
	cp ~/Sites/fm/hpsi/1/bundle.min.js components0
	cp ~/Sites/fm/hpsi/data/data.csv data

gif:
	cp ~/Sites/fm/hpsi/2/hpsi.gif gif   # animated once through
	cp ~/Sites/fm/hpsi/2/final.gif gif  # continuous loop
	cp ~/Sites/fm/hpsi/2/final.png gif  # PNG of final image

hpsi2:
	cp ~/Sites/fm/hpsi/2/final.gif hpsi/2
	cp ~/Sites/fm/hpsi/2/final.png hpsi/2
	cp ~/Sites/fm/hpsi/2/hpsi.gif hpsi/2

hpsi1:
	cp ~/Sites/fm/hpsi/1/index.html hpsi/1
	cp ~/Sites/fm/hpsi/1/styles.css hpsi/1
	cp ~/Sites/fm/hpsi/1/bundle.min.js hpsi/1
	cp ~/Sites/fm/hpsi/data/data.csv hpsi/data

hpsi0:
	cp ~/Sites/fm/hpsi/0/index.html hpsi/0
	cp ~/Sites/fm/hpsi/0/styles.css hpsi/0
	cp ~/Sites/fm/hpsi/0/bundle.min.js hpsi/0
	cp ~/Sites/fm/hpsi/data/data.csv hpsi/data

map1:
	cp ../../fmap1/*.png map1
	cp ../../fmap1/*.css map1
	cp ../../fmap1/index.html map1
	cp ../../fmap1/map.html map1
	cp ../../fmap1/data.json map1
	cp ../../fmap1/single.svg map1
	cp ../../fmap1/bundle.min.js map1

map2:
	cp ../../fmap2/*.png map2
	cp ../../fmap2/*.css map2
	cp ../../fmap2/index.html map2
	cp ../../fmap2/map.html map2
	cp ../../fmap2/data.json map2
	cp ../../fmap2/single.svg map2
	cp ../../fmap2/bundle.min.js map2

fm5:
	cp ../../fm5/index.html 5
	cp ../../fm5/*.csv 5
	cp ../../fm5/bundle.min.js 5

fm6:
	cp ../../fm6/index.html 6
	cp ../../fm6/*.csv 6
	cp ../../fm6/bundle.min.js 6

fm7:
	cp ../../fm7/index.html 7
	cp ../../fm7/*.csv 7
	cp ../../fm7/bundle.min.js 7

fm8:
	cp ../../fm8/index.html 8
	cp ../../fm8/*.csv 8
	cp ../../fm8/*.css 8
	cp ../../fm8/bundle.min.js 8

fm9:
	cp ../../fm9/index.html 9
	cp ../../fm9/styles.css 9
	cp ../../fm9/*.csv 9
	cp ../../fm9/*.css 9
	cp ../../fm9/bundle.min.js 9

fm10:
	cp ../../fm10/index.html 10
	cp ../../fm10/styles.css 10
	cp ../../fm10/*.csv 10
	cp ../../fm10/*.css 10
	cp ../../fm10/bundle.min.js 10

fm11:
	cp ../../fm11/index.html 11
	cp ../../fm11/styles.css 11
	cp ../../fm11/*.csv 11
	cp ../../fm11/*.css 11
	cp ../../fm11/bundle.min.js 11

fm12:
	cp ../../fm12/index.html 12
	cp ../../fm12/styles.css 12
	cp ../../fm12/*.csv 12
	cp ../../fm12/*.css 12
	cp ../../fm12/bundle.min.js 12

fm13:
	cp ../../fm13/index.html 13
	cp ../../fm13/styles.css 13
	cp ../../fm13/*.csv 13
	cp ../../fm13/*.css 13
	cp ../../fm13/bundle.min.js 13

fm16:
	cp ../../fm16/index.html 16
	cp ../../fm16/styles.css 16
	cp ../../fm16/*.json 16
	cp ../../fm16/*.css 16
	cp ../../fm16/bundle.min.js 16

fm17:
	cp ../../fm17/index.html 17
	cp ../../fm17/data.json 17
	cp ../../fm17/*.css 17
	cp ../../fm17/bundle.min.js 17

fm18:
	cp ../../fm18/index.html 18
	cp ../../fm18/data.json 18
	cp ../../fm18/*.css 18
	cp ../../fm18/bundle.min.js 18

fm19:
	cp ../../fm19/index.html 19
	cp ../../fm19/data.json 19
	cp ../../fm19/*.css 19
	cp ../../fm19/bundle.min.js 19

fm20:
	cp ../../fm20/index.html 20
	cp ../../fm20/data.json 20
	cp ../../fm20/*.css 20
	cp ../../fm20/bundle.min.js 20

fm21:
	cp ../../fm21/index.html 21
	cp ../../fm21/data.json 21
	cp ../../fm21/*.css 21
	cp ../../fm21/bundle.min.js 21

fm22:
	cp ../../fm22/index.html 22
	cp ../../fm22/data.json 22
	cp ../../fm22/*.css 22
	cp ../../fm22/bundle.min.js 22

fm27:
	cp ../../fm/millenials/27/millenials.zip millenials/27

fm25:
	cp ../../fm25/index.html 25
	cp ../../fm25/data.json 25
	cp ../../fm25/*.css 25
	cp ../../fm25/bundle.min.js 25

fm23:
	cp ../../fm23/index.html 23
	cp ../../fm23/data.json 23
	cp ../../fm23/*.css 23
	cp ../../fm23/bundle.min.js 23

fms3:
	cp ../../fms3/index.html s3
	cp ../../fms3/styles.css s3
	cp ../../fms3/*.json s3
	cp ../../fms3/bundle.min.js s3

fms2:
	cp ../../fms2/index.html s2
	cp ../../fms2/styles.css s2
	cp ../../fms2/*.json s2
	cp ../../fms2/bundle.min.js s2

fms1:
	cp ../../fms1/index.html s1
	cp ../../fms1/styles.css s1
	cp ../../fms1/*.json s1
	cp ../../fms1/bundle.min.js s1

fms:
	cp ../../fms0/index.html s
	cp ../../fms0/styles.css s
	cp ../../fms0/*.json s
	cp ../../fms0/bundle.min.js s

fmr4:
	cp ../../fmr4/index.html r4
	cp ../../fmr4/styles.css r4
	cp ../../fmr4/*.json r4
	cp ../../fmr4/bundle.min.js r4

fmr3:
	cp ../../fmr3/index.html r3
	cp ../../fmr3/*.json r3
	cp ../../fmr3/bundle.min.js r3

fmr1:
	cp ../../fmr1/index.html r1
	cp ../../fmr1/*.json r1
	cp ../../fmr1/bundle.min.js r1
