all: fm5 fm6 fm7 fm8 fm9 fm10 fm11 fm12

.PHONY: fm5 fm6 fm7 fm8 fm9 fm10 fm11 fm12

fm5:
	cp ../../fm5/index.html 5
	cp ../../fm5/*.csv 5
	cp ../../fm5/bundle.min.js 5

fm6:
	cp ../../fm6/index.html 6
	cp ../../fm6/*.csv 6
	cp ../../fm6/bundle.min.js 6

fm7:
	cp ../../fm7/index.html 7
	cp ../../fm7/*.csv 7
	cp ../../fm7/bundle.min.js 7

fm8:
	cp ../../fm8/index.html 8
	cp ../../fm8/*.csv 8
	cp ../../fm8/*.css 8
	cp ../../fm8/bundle.min.js 8

fm9:
	cp ../../fm9/index.html 9
	cp ../../fm9/styles.css 9
	cp ../../fm9/*.csv 9
	cp ../../fm9/*.css 9
	cp ../../fm9/bundle.min.js 9

fm10:
	cp ../../fm10/index.html 10
	cp ../../fm10/styles.css 10
	cp ../../fm10/*.csv 10
	cp ../../fm10/*.css 10
	cp ../../fm10/bundle.min.js 10

fm11:
	cp ../../fm11/index.html 11
	cp ../../fm11/styles.css 11
	cp ../../fm11/*.csv 11
	cp ../../fm11/*.css 11
	cp ../../fm11/bundle.min.js 11

fm12:
	cp ../../fm12/index.html 12
	cp ../../fm12/styles.css 12
	cp ../../fm12/*.csv 12
	cp ../../fm12/*.css 12
	cp ../../fm12/bundle.min.js 12

fm13:
	cp ../../fm13/index.html 13
	cp ../../fm13/styles.css 13
	cp ../../fm13/*.csv 13
	cp ../../fm13/*.css 13
	cp ../../fm13/bundle.min.js 13
