all: tree5

.PHONY: tree1 tree2 tree3 tree4 tree5

tree1:
	cp ../../tree1/index.html tree1
	cp ../../tree1/*.csv tree1
	cp ../../tree1/*.css tree1
	cp ../../tree1/bundle.min.js tree1

tree2:
	cp ../../tree2/index.html tree2
	cp ../../tree2/*.csv tree2
	cp ../../tree2/*.css tree2
	cp ../../tree2/bundle.min.js tree2

tree3:
	cp ../../tree3/index.html tree3
	cp ../../tree3/*.csv tree3
	cp ../../tree3/*.css tree3
	cp ../../tree3/bundle.min.js tree3

tree4:
	cp ../../tree4/index.html tree4
	cp ../../tree4/*.css tree4
	cp ../../tree4/bundle.min.js tree4

tree5:
	cp ../../tree5/index.html tree5
	cp ../../tree5/*.csv tree5
	cp ../../tree5/*.css tree5
	cp ../../tree5/bundle.min.js tree5
