# To create the graphic...
# 
# 1. make 
# 2. vi index.html -- look for d3.min.js in the local directory
#

all:
	cp ~/Sites/fm/ga/7/index.html .
	cp ~/Sites/fm/ga/7/barChart.js .
	cp ~/Sites/fm/ga/7/script.js .
	cp ~/Sites/fm/ga/7/styles.css .
	cp ~/Sites/fm/ga/7/jul2016.json .
	cp ~/Sites/fm/ga/7/dec2015.json .
	cp ~/Sites/d3/d3.min.js .
