all: plss plss3 shale3 earthquake5 colorado6 colorado7 colorado8 colorado9 colorado12 colorado13 colorado14 colorado15 colorado16 colorado17 colorado20 colorado23 colorado24 colorado25 colorado26 colorado27 colorado28

.PHONY: plss plss3 shale3 earthquake5

plss:
	cp ../../../plss/index.html ./plss
	cp ../../../plss/co.json ./plss
	cp ../../../plss/first.json ./plss
	cp ../../../plss/twnshp.json ./plss
	cp ../../../plss/bundle.min.js ./plss

plss3:
	cp ../../../plss3/index.html ./plss3
	cp ../../../plss3/co.json ./plss3
	cp ../../../plss3/countykeys.json ./plss3
	cp ../../../plss3/data/twnshp.json ./plss3/data
	cp ../../../plss3/data/topojson/*.json ./plss3/data/topojson
	cp ../../../plss3/bundle.min.js ./plss3

shale3:
	cp ../../../shale3/index.html ./shale3
	cp ../../../shale3/shalegas.json ./shale3
	cp ../../../shale3/us.json ./shale3
	cp ../../../shale3/bundle.min.js ./shale3

earthquake5:
	cp ../../../earthquake5/index.html ./earthquake5
	cp ../../../earthquake5/shalegasplay.json ./earthquake5
	cp ../../../earthquake5/co.json ./earthquake5
	cp ../../../earthquake5/quakes.json ./earthquake5
	cp ../../../earthquake5/styles.css ./earthquake5
	cp ../../../earthquake5/bundle.min.js ./earthquake5

colorado6:
	cp ../../../colorado6/index.html ./6
	cp ../../../colorado6/co.json ./6
	cp ../../../colorado6/file.json ./6
	cp ../../../colorado6/shalegasplay.json ./6
	cp ../../../colorado6/bundle.min.js ./6

colorado7:
	cp ../../../colorado7/index.html ./7
	cp ../../../colorado7/file.json ./7
	cp ../../../colorado7/bundle.min.js ./7

colorado8:
	cp ../../../colorado8/index.html ./8
	cp ../../../colorado8/co.json ./8
	cp ../../../colorado8/file.json ./8
	cp ../../../colorado8/bundle.min.js ./8

colorado9:
	cp ../../../colorado9/index.html ./9
	cp ../../../colorado9/co.json ./9
	cp ../../../colorado9/file.json ./9
	cp ../../../colorado9/bundle.min.js ./9

colorado12:
	cp ../../../colorado12/index.html ./12
	cp ../../../colorado12/co.json ./12
	cp ../../../colorado12/data.json ./12
	cp ../../../colorado12/shalegasplay.json ./12
	cp ../../../colorado12/bundle.min.js ./12

colorado13:
	cp ../../../colorado13/index.html ./13
	cp ../../../colorado13/co.json ./13
	cp ../../../colorado13/data.json ./13
	cp ../../../colorado13/shalegasplay.json ./13
	cp ../../../colorado13/styles.css ./13
	cp ../../../colorado13/bundle.min.js ./13

colorado14:
	cp ../../../colorado14/index.html ./14
	cp ../../../colorado14/co.json ./14
	cp ../../../colorado14/data.json ./14
	cp ../../../colorado14/quakes.json ./14
	cp ../../../colorado14/shalegasplay.json ./14
	cp ../../../colorado14/styles.css ./14
	cp ../../../colorado14/bundle.min.js ./14

colorado15:
	cp ../../../colorado15/index.html ./15
	cp ../../../colorado15/co.json ./15
	cp ../../../colorado15/data.json ./15
	cp ../../../colorado15/quakes.json ./15
	cp ../../../colorado15/shalegasplay.json ./15
	cp ../../../colorado15/styles.css ./15
	cp ../../../colorado15/bundle.min.js ./15

colorado16:
	cp ../../../colorado16/index.html ./16
	cp ../../../colorado16/co.json ./16
	cp ../../../colorado16/data.json ./16
	cp ../../../colorado16/quakes.json ./16
	cp ../../../colorado16/shalegasplay.json ./16
	cp ../../../colorado16/styles.css ./16
	cp ../../../colorado16/bundle.min.js ./16

colorado17:
	cp ../../../colorado17/index.html ./17
	cp ../../../colorado17/co.json ./17
	cp ../../../colorado17/adams_first.json ./17
	cp ../../../colorado17/adams_twnshp.json ./17
	cp ../../../colorado17/adams_ladesc.json ./17
	cp ../../../colorado17/bundle.min.js ./17

colorado20:
	cp ../../../colorado20/index.html ./20
	cp ../../../colorado20/co.json ./20
	cp ../../../colorado20/bundle.min.js ./20

colorado23:
	cp ../../../colorado23/index.html ./23
	cp ../../../colorado23/co.json ./23
	cp ../../../colorado23/quakes.json ./23
	cp ../../../colorado23/data.json ./23
	cp ../../../colorado23/shalegasplay.json ./23
	cp ../../../colorado23/bundle.min.js ./23

colorado24:
	cp ../../../colorado24/index.html ./24
	cp ../../../colorado24/co.json ./24
	cp ../../../colorado24/quakes.json ./24
	cp ../../../colorado24/data.json ./24
	cp ../../../colorado24/shalegasplay.json ./24
	cp ../../../colorado24/bundle.min.js ./24

colorado25:
	cp ../../../colorado25/index.html ./25
	cp ../../../colorado25/co.json ./25
	cp ../../../colorado25/quakes.json ./25
	cp ../../../colorado25/data.json ./25
	cp ../../../colorado25/shalegasplay.json ./25
	cp ../../../colorado25/bundle.min.js ./25

colorado26:
	cp ../../../colorado26/index.html ./26
	cp ../../../colorado26/co.json ./26
	cp ../../../colorado26/quakes.json ./26
	cp ../../../colorado26/data.json ./26
	cp ../../../colorado26/shalegasplay.json ./26
	cp ../../../colorado26/data/countykeys.json ./26/data
	cp ../../../colorado26/data/twnshp.json ./26/data
	cp ../../../colorado26/data/topojson/*.json ./26/data/topojson
	cp ../../../colorado26/bundle.min.js ./26

colorado27:
	cp ../../../colorado27/index.html ./27
	cp ../../../colorado27/co.json ./27
	cp ../../../colorado27/quakes.json ./27
	cp ../../../colorado27/data.json ./27
	cp ../../../colorado27/shalegasplay.json ./27
	cp ../../../colorado27/data/countykeys.json ./27/data
	cp ../../../colorado27/data/twnshp.json ./27/data
	cp ../../../colorado27/data/topojson/*.json ./27/data/topojson
	cp ../../../colorado27/bundle.min.js ./27

colorado28:
	cp ../../../colorado28/index.html ./28
	cp ../../../colorado28/co.json ./28
	cp ../../../colorado28/quakes.json ./28
	cp ../../../colorado28/data.json ./28
	cp ../../../colorado28/shalegasplay.json ./28
	cp ../../../colorado28/signin.css ./28
	cp ../../../colorado28/data/countykeys.json ./28/data
	cp ../../../colorado28/data/twnshp.json ./28/data
	cp ../../../colorado28/data/topojson/*.json ./28/data/topojson
	cp ../../../colorado28/bundle.min.js ./28
